### ISSUE TITLE
Resampling issue

### ISSUE THREAD

**Issue by Mahaals** [voreille/hecktor#3]
I'm facing a problem in running python `src/resampling/cli_resampling.py` line.

```
C:\Users\x\y\hecktor_project\hecktor-master1>python src/resampling/cli_resampling.py
2020-07-02 22:30:28,050 - __main__ - INFO - Resampling
resampling is (1.0, 1.0, 1.0)
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\mahaw\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\indexes\base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'hecktor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mahaw\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\mahaw\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "c:\users\x\y\hecktor_project\hecktor-master1\src\resampling\resampling.py", line 35, in __call__
    bb = (self.bb_df.loc[patient_name, 'x1'], self.bb_df.loc[patient_name,
  File "C:\Users\mahaw\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\indexing.py", line 1762, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Users\mahaw\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\indexing.py", line 1272, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "C:\Users\mahaw\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\indexing.py", line 1389, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "C:\Users\mahaw\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\indexing.py", line 1965, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "C:\Users\mahaw\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\indexing.py", line 625, in _get_label
    return self.obj._xs(label, axis=axis)
  File "C:\Users\mahaw\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\generic.py", line 3537, in xs
    loc = self.index.get_loc(key)
  File "C:\Users\mahaw\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\indexes\base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'hecktor'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/resampling/cli_resampling.py", line 76, in <module>
    main()
  File "C:\Users\mahaw\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\mahaw\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\mahaw\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\mahaw\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "src/resampling/cli_resampling.py", line 68, in main
    p.map(resampler, files_list)
  File "C:\Users\mahaw\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\mahaw\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
KeyError: 'hecktor'

```

**Comment by voreille** [comment]
Hi,

We did not test the code on Windows, so I would expect that the error comes from the path. You can try `python cli_resampling.py <path to input folder> <path to output folder> <path to bbox.csv>. If it does not work, you can use any other tools to load and preprocess the data.
Sorry for the inconvenience.

Best,

Valentin

**Comment by Hamid-Naderi** [comment]
@Mahaals have you solved the problem? I'm facing the same error!

**Comment by resonance20** [comment]
The problem I think stems from the resampler looking for `/` as a delimiter, whereas Windows uses `\`. I solved this by changing the following code snippet:
`files_list = [
        f for f in glob.glob(input_folder + '/**/*.nii.gz', recursive=True)
    ]`

to 

`files_list = [
        f for f in glob.glob(input_folder + '/**/*.nii.gz', recursive=True)
    ]
    for i, file in enumerate(files_list):
        files_list[i] = file.replace('\\', '/')`

in cli_resampling.py. Perhaps this will help for other Windows users.

**Comment by Mahaals** [comment]
> The problem I think stems from the resampler looking for `/` as a delimiter, whereas Windows uses `\`. I solved this by changing the following code snippet:
> `files_list = [ f for f in glob.glob(input_folder + '/**/*.nii.gz', recursive=True) ]`
> 
> to
> 
> `files_list = [ f for f in glob.glob(input_folder + '/**/*.nii.gz', recursive=True) ] for i, file in enumerate(files_list): files_list[i] = file.replace('\\', '/')`
> 
> in cli_resampling.py. Perhaps this will help for other Windows users.

This solved the problem!
Thank you @resonance20

**Comment by Mahaals** [comment]
@Hamid-Naderi  Please see the above solution.
